### ISSUE TITLE
How is upstream integration with Gutenberg going?

### ISSUE THREAD

**Issue by gziolo** [front/gutenberg#4]
Hello, I'm one of the core developers of Gutenberg. I found your repository on Twitter through this talk description: https://www.drupaleurope.org/session/introducing-gutenberg-content-editor-drupal-8.

I noticed that your latest commit pulled from upstream repository is dated July 2nd. In the meantime we reorganized the structure of the code to make it easier to use outside of WordPress. I think this will decrease the number of globals that you need to provide to make it work. We also published to npm almost all modules used in Gutenberg. You can watch progress here:
https://github.com/WordPress/gutenberg/issues/3955
Long term, you should rather opt for consuming to those packages rather than maintaining your own fork. We are happy to discuss extensibility points which would help to make your integration easier. You can read about all documented ways you can extend Gutenberg as of today in here: https://wordpress.org/gutenberg/handbook/extensibility/.

If you have any questions or feedback to share reach out to us. You can find us on Slack in [#core-editor channel on Make WordPress](https://wordpress.slack.com/messages/core-editor/). Have fun integrating Gutenberg.

**Comment by SofiaSousa** [comment]
Hi @gziolo!

**Comment by SofiaSousa** [comment]
Hi @gziolo,

Actually, we've been trying another approach instead of forking **Wordpress/gutenberg** repo because it was getting hard to maintain the code and our overrides. So, I've decided to not fork Wodpress/gutenberg repo but use it as a dependency of [gutenberg-js](https://github.com/front/gutenberg-js) and just maintain our overrides.

We're still using Gutenberg 3.2.0 (from [#3d009d2)](https://github.com/WordPress/gutenberg/commit/3d009d29bd6a23a906b07907311e6a995246fb02), but I hope we can keep following the latest releases.

**Comment by gziolo** [comment]
Yes, maintaining fork is super hard. This might be a better idea to use it as a dependency in the short term. However, it might not work properly with the latest version of Gutenberg because we use Lerna 3.x which works with local packages, so you might run into issues with that. When publishing to npm it is rewritten to the proper version number of each package. Anyway, you will get to it soon. Have fun and good luck. I will watch the progress in `gutenberg-js` repository 👋
